### PR TITLE
Clickable happygraph (#19)

### LINKED ISSUE #19: Mental health visual interactivity
As a user, I would like to see what blog posts the visualization comes from, so that I may better understand my mental health visualization.
Acceptance criteria:
Mental health visualization shall have links to user’s blog posts.
Links should take user to the respective pages.
The graph should respond to clicks within 30 seconds.

Story source:  SRS - FR18
Estimate:  5 man-hours
Risk: Low
 Value: Low
Priority: L

### PR DESCRIPTION
**Pull request by markiragoldberg**
This PR allows the user to click the happygraph bars to go to the corresponding posts.

Resolves #19.

I put the javascript in the html file to avoid having to set up django's staticfiles just for this one script.

### CODE REVIEW

**Review by perpetual-pelican — COMMENTED** [review]
Does this add anything new, or did you just move stuff around?

**Review by akohli96 — CHANGES_REQUESTED** [review]
Mark would it not be better to move things to .js instead of .html

**Review by akohli96 — APPROVED** [review]
Just saw your static files comment

**Review by perpetual-pelican — APPROVED** [review]
As far as I can tell, this looks okay.

**Comment by akohli96** [comment]
I will merge it in after @foxstrunk reviews it.

**Comment by akohli96** [comment]
@foxstrunk update on this?

**Comment by akohli96** [comment]
@foxstrunk we wont be able to merge @markiragoldberg's work into the master branch if you dont review it.

**Pull request merged**
