### PR TITLE
Added tests and made login required for password change page

### PR DESCRIPTION
**Pull request by perpetual-pelican**
Tests password change page and Bot's fetch_quote method. Also tests help response for Bot's process_message method.

### CODE REVIEW

**Comment by akohli96** [comment]
@pelikenesis there is no gurantee our quote fetch will work since the get request may fail. Its probably safer to test for something else rn

**Comment by perpetual-pelican** [comment]
@akohli96 okay

**Comment by perpetual-pelican** [comment]
@akohli96 better now?

**Review by akohli96 — APPROVED** [review]
All good here

**Comment by akohli96** [comment]
@markiragoldberg  merge this in after your review

**Review by markiragoldberg — APPROVED** [review]
Pro tests from Djangocious J

**Pull request merged**
